name: Rebuild ReadTheDocs

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - uses: actions/checkout@v2

    - name: Trigger ReadTheDocs build
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
        curl -X POST -H "Authorization: token $READTHEDOCS_TOKEN" https://readthedocs.org/api/v3/projects/big-graph-dataset/builds/